# Generated by Django 5.1.7 on 2025-05-05 09:37

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название компании')),
                ('site', models.URLField(blank=True, null=True, verbose_name='Сайт компании')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message="Номер телефона должен быть в формате: '+999999999'. До 15 цифр.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Телефон компании')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email компании')),
                ('industry', models.CharField(blank=True, max_length=255, null=True, verbose_name='Направленность')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание компании')),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('full_name', models.CharField(max_length=255, verbose_name='Полное ФИО')),
                ('home_phone', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message="Номер телефона должен быть в формате: '+999999999'. До 15 цифр.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Домашний телефон')),
                ('work_phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message="Номер телефона должен быть в формате: '+999999999'. До 15 цифр.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Рабочий телефон')),
                ('work_email', models.EmailField(max_length=254, unique=True, verbose_name='Рабочая почта')),
                ('home_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Домашняя почта')),
                ('role', models.CharField(choices=[('owner', 'Собственник'), ('sales_manager', 'Менеджер по продажам'), ('project_manager', 'Проектный менеджер'), ('account_manager', 'Аккаунт менеджер'), ('logistic', 'Логист'), ('engineer', 'Инженер'), ('warehouse_worker', 'Кладовщик'), ('accountant', 'Бухгалтер'), ('lawyer', 'Юрист'), ('top_manager', 'ТОП Менеджер'), ('call_operator', 'Оператор кол-центра')], default='sales_manager', max_length=20, verbose_name='Роль')),
                ('department', models.CharField(choices=[('warehouses', 'ШМБ'), ('racks', 'Стеллажные системы'), ('warehouses_machines', 'Складская техника'), ('plastic_containers', 'Пластиковая тара'), ('trash_bins', 'Мусорные баки'), ('sorting_systems', 'Системы сортировки'), ('automation', 'Автоматизация'), ('services', 'Сервисные услуги'), ('administrations', 'Администрация'), ('logistics', 'Логистика'), ('finance', 'Финансы и бухгалтерия'), ('marketing', 'Маркетинг')], default='administrations', max_length=50, verbose_name='Департамент')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='ФИО Контакта')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message="Номер телефона должен быть в формате: '+999999999'. До 15 цифр.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('messenger', models.CharField(blank=True, choices=[('telegram', 'Telegram'), ('viber', 'Viber'), ('whatsapp', 'WatsApp'), ('signal', 'Signal')], max_length=100, null=True, verbose_name='Мессенджер')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts', to='crm.company', verbose_name='Компания')),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='main_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_for_companies', to='crm.contact', verbose_name='Главный контакт'),
        ),
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО контакта')),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message="Номер телефона должен быть в формате: '+999999999'. До 15 цифр.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('messenger', models.CharField(blank=True, choices=[('telegram', 'Telegram'), ('viber', 'Viber'), ('whatsapp', 'WatsApp'), ('signal', 'Signal')], max_length=100, null=True, verbose_name='Мессенджер')),
                ('company_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название компании клиента')),
                ('company_site', models.URLField(blank=True, null=True, verbose_name='Сайт компании')),
                ('need_description', models.TextField(verbose_name='Описание потребности клиента')),
                ('departments', models.JSONField(blank=True, null=True, verbose_name='Выбранные направления')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата обращения')),
                ('status', models.CharField(choices=[('wait_conversion', 'Ожидает конвертации'), ('pending', 'В ожидании'), ('in_progress', 'В работе'), ('archived', 'В архиве')], default='wait_conversion', max_length=20, verbose_name='Статус обращения')),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call_operator', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный оператор')),
            ],
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('need', models.TextField(verbose_name='Потребность')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Название лида')),
                ('department_assignments', models.JSONField(blank=True, null=True, verbose_name='Ответственные')),
                ('status', models.CharField(choices=[('new', 'Новый'), ('in_progress', 'В работе'), ('non_active', 'Не активен')], default='new', max_length=20, verbose_name='Статус')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='crm.contact', verbose_name='Контакт')),
                ('participants', models.ManyToManyField(blank=True, related_name='leads_participating', to=settings.AUTH_USER_MODEL, verbose_name='Участники')),
            ],
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('warehouses', 'ШМБ'), ('racks', 'Стеллажные системы'), ('warehouses_machines', 'Складская техника'), ('plastic_containers', 'Пластиковая тара'), ('trash_bins', 'Мусорные баки'), ('sorting_systems', 'Системы сортировки'), ('automation', 'Автоматизация'), ('services', 'Сервисные услуги'), ('administrations', 'Администрация'), ('logistics', 'Логистика'), ('finance', 'Финансы и бухгалтерия'), ('marketing', 'Маркетинг')], max_length=50, verbose_name='Департамент')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Название сделки')),
                ('validated_need', models.TextField(blank=True, null=True, verbose_name='Проверенная потребность')),
                ('contract_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Стоимость контракта')),
                ('status', models.CharField(choices=[('need', 'Не обработана'), ('identifying_need', 'Выявление потребности'), ('solution', 'Подготовка решения'), ('commercial_offer', 'Презентация КП'), ('objections', 'Работа с возражениями'), ('auction', 'Торг'), ('contract', 'Подписание договора'), ('prepay', 'Получение предоплаты'), ('partners', 'Работа с подрядчиками'), ('logistics', 'Логистика'), ('implementation', 'Реализация'), ('closing', 'Закрытие сделки')], default='need', max_length=20, verbose_name='Статус')),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_deals', to=settings.AUTH_USER_MODEL, verbose_name='Аккаунт')),
                ('participants', models.ManyToManyField(blank=True, related_name='deals_participating', to=settings.AUTH_USER_MODEL, verbose_name='Соучастники')),
                ('responsible', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_deals', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='crm.lead', verbose_name='Лид')),
            ],
        ),
        migrations.CreateModel(
            name='NextStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Описание следующего шага')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('deadline', models.DateTimeField(blank=True, null=True, verbose_name='Крайний срок')),
                ('status', models.CharField(choices=[('open', 'Открыта'), ('in_progress', 'В работе'), ('done', 'Выполнена'), ('canceled', 'Отменена')], default='open', max_length=20, verbose_name='Статус следующего шага')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель')),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='next_steps', to='crm.deal', verbose_name='Сделка')),
            ],
        ),
        migrations.CreateModel(
            name='DealEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('comment', 'Комментарий'), ('phone', 'Телефонный разговор'), ('client_response', 'Ответ клиента'), ('meeting', 'Встреча'), ('first_contact', 'Первый контакт')], max_length=50, verbose_name='Тип события')),
                ('content', models.TextField(verbose_name='Содержание события')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='crm.deal', verbose_name='Сделка')),
                ('next_step', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.nextstep', verbose_name='Следующий шаг')),
            ],
        ),
    ]
