# Generated by Django 5.1.7 on 2025-05-07 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealevent',
            name='content',
            field=models.TextField(default='Передано от оператора', verbose_name='Содержание события'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='status',
            field=models.CharField(choices=[('wait_conversion', 'Ожидает конвертации'), ('pending', 'В ожидании'), ('in_progress', 'В работе'), ('archived', 'В архиве')], default='pending', max_length=20, verbose_name='Статус обращения'),
        ),
        migrations.AlterField(
            model_name='nextstep',
            name='description',
            field=models.TextField(verbose_name='Описание следующего шага'),
        ),
    ]
