# Generated by Django 5.1.7 on 2025-05-07 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_alter_dealevent_content_alter_inquiry_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealevent',
            name='content',
            field=models.TextField(verbose_name='Содержание события'),
        ),
        migrations.AlterField(
            model_name='nextstep',
            name='description',
            field=models.TextField(verbose_name='Описание следующего шага'),
        ),
    ]
