# Generated by Django 5.1.7 on 2025-05-08 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_alter_dealevent_content_alter_nextstep_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='inquiry',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lead', to='crm.inquiry', verbose_name='Обращение'),
        ),
    ]
