# Generated by Django 5.1.7 on 2025-05-08 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_lead_inquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealevent',
            name='pipeline',
            field=models.CharField(choices=[('need', 'Не обработана'), ('identifying_need', 'Выявление потребности'), ('solution', 'Подготовка решения'), ('commercial_offer', 'Презентация КП'), ('objections', 'Работа с возражениями'), ('auction', 'Торг'), ('contract', 'Подписание договора'), ('prepay', 'Получение предоплаты'), ('partners', 'Работа с подрядчиками'), ('logistics', 'Логистика'), ('implementation', 'Реализация'), ('closing', 'Закрытие сделки')], default=1, max_length=20, verbose_name='Стадия сделки при событии'),
            preserve_default=False,
        ),
    ]
