# Generated by Django 5.1.7 on 2025-05-14 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_task_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('low', 'Стандартный'), ('high', 'Высокий')], default='medium', max_length=20, verbose_name='Приоритет'),
        ),
    ]
