# Generated by Django 5.1.7 on 2025-05-23 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_alter_task_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('approval', 'Согласование'), ('payment', 'Оплата'), ('delivery', 'Доставка'), ('universal', 'Универсальная'), ('step', 'Шаг')], default='universal', max_length=20, verbose_name='Тип задачи'),
        ),
    ]
