# Generated by Django 5.1.7 on 2025-05-24 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_alter_task_task_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('low', 'Стандартный'), ('high', 'Высокий')], default='low', max_length=20, verbose_name='Приоритет'),
        ),
    ]
