# Generated by Django 5.1.7 on 2025-05-30 12:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_alter_task_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата создания лида'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='company',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон компании'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='home_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Домашний телефон'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='work_phone',
            field=models.CharField(max_length=20, verbose_name='Рабочий телефон'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Телефон'),
        ),
    ]
