# Generated by Django 5.1.7 on 2025-06-03 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0012_lead_created_at_alter_company_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='source',
            field=models.CharField(choices=[('inquiry', 'Из обращения'), ('manual', 'Ручное создание')], default='inquiry', max_length=20, verbose_name='Источник лида'),
        ),
    ]
