# Generated by Django 5.1.7 on 2025-06-09 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0013_lead_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='inquiry',
            name='phone',
        ),
        migrations.CreateModel(
            name='InquiryPhoneNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('phone_type', models.CharField(choices=[('WORK_PRIMARY', 'Рабочий'), ('WORK_SECONDARY', 'Дополнительный'), ('MOBILE', 'Личный')], default='MOBILE', max_length=20, verbose_name='Тип телефона')),
                ('inquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_numbers', to='crm.inquiry', verbose_name='Обращение')),
            ],
            options={
                'verbose_name': 'Номер телефона (Обращение)',
                'verbose_name_plural': 'Номера телефонов (Обращения)',
                'unique_together': {('inquiry', 'phone_number'), ('inquiry', 'phone_type')},
            },
        ),
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('phone_type', models.CharField(choices=[('WORK_PRIMARY', 'Рабочий'), ('WORK_SECONDARY', 'Дополнительный'), ('MOBILE', 'Личный')], default='MOBILE', max_length=20, verbose_name='Тип телефона')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_numbers', to='crm.contact', verbose_name='Контакт')),
            ],
            options={
                'verbose_name': 'Номер телефона',
                'verbose_name_plural': 'Номера телефонов',
                'unique_together': {('contact', 'phone_number'), ('contact', 'phone_type')},
            },
        ),
    ]
