# Generated by Django 5.1.7 on 2025-06-09 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0014_remove_contact_phone_remove_inquiry_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiryphonenumber',
            name='phone_type',
            field=models.CharField(choices=[('WORK_PRIMARY', 'Рабочий'), ('WORK_SECONDARY', 'Дополнительный'), ('MOBILE', 'Личный')], max_length=20, verbose_name='Тип телефона'),
        ),
        migrations.AlterField(
            model_name='phonenumber',
            name='phone_type',
            field=models.CharField(choices=[('WORK_PRIMARY', 'Рабочий'), ('WORK_SECONDARY', 'Дополнительный'), ('MOBILE', 'Личный')], max_length=20, verbose_name='Тип телефона'),
        ),
    ]
