# Generated by Django 5.1.7 on 2025-06-15 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0015_alter_inquiryphonenumber_phone_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('approval', 'Согласование'), ('payment', 'Оплата'), ('delivery', 'Доставка'), ('universal', 'Универсальная'), ('step', 'Шаг'), ('stage_funnel', 'Воронка')], default='universal', max_length=20, verbose_name='Тип задачи'),
        ),
    ]
