# Generated by Django 5.2.3 on 2025-07-29 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0018_alter_task_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='status',
            field=models.CharField(choices=[('need', 'Не обработана'), ('identifying_need', 'Выявление потребности'), ('solution', 'Подготовка решения'), ('commercial_offer', 'Бюджетирование'), ('objections', 'Презентация КП'), ('auction', 'Торг'), ('contract', 'Подписание договора'), ('prepay', 'Получение предоплаты'), ('partners', 'Работа с подрядчиками'), ('logistics', 'Логистика'), ('implementation', 'Реализация'), ('closing', 'Закрытие сделки')], default='need', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='dealevent',
            name='pipeline',
            field=models.CharField(choices=[('need', 'Не обработана'), ('identifying_need', 'Выявление потребности'), ('solution', 'Подготовка решения'), ('commercial_offer', 'Бюджетирование'), ('objections', 'Презентация КП'), ('auction', 'Торг'), ('contract', 'Подписание договора'), ('prepay', 'Получение предоплаты'), ('partners', 'Работа с подрядчиками'), ('logistics', 'Логистика'), ('implementation', 'Реализация'), ('closing', 'Закрытие сделки')], max_length=20, verbose_name='Стадия сделки при событии'),
        ),
    ]
